console.log("My_first_project_on_console");
var first_name = "Ranya";
var last_name = "Chaudhary";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 10;
var b = 20;
var add = a+b;
console.log(add);
var sub = a-b;
console.log(sub);
var divide = a/b;
console.log(divide);